### PR TITLE
My new shiny feature

### PR DESCRIPTION
**Pull request by dannysmith**
This is for code review on the new shiny feature.

### CODE REVIEW

**Comment by dannysmith** [comment]
@dianaosmani Code review?

**Comment by dianaosmani** [comment]
change your name

**Comment by dannysmith** [comment]
Looks good, except the method name `doo_foo` is a bit weird. Maybe change it?

**Comment by dannysmith** [comment]
Do the following:

- [ ] One
- [ ] Two

We discussed tbhat in #2.

**Comment by dianaosmani** [comment]
`foo_do`

**Pull request merged**
